### ISSUE TITLE
Create the project manager package for handling compilation and project generation

### ISSUE THREAD

**Issue by hrszpuk** [hrszpuk/rectx#26]
The project manager is the core feature that will be utilised by the end user. This is because this package handles compilation and project generation. It will also use other modules such as templates, config, and utilities.

## Project Manager features
- Handles `new` prompt
- Uses templates + config modules to generate projects
- Generates project.rectx (config sub-package?)
- Builds the project with `build` handler
- Runs the project with `run` handler
- Run/build will read profiles from project.rectx before executing

## Todo
- [x] Create project_manager package.
- [x] Create front.go for `new`, `build`, and `run`.
- [x] Create config sub-package for handling project.rectx files.
- [x] Create config structure
- [x] Set up load/dump for config
- [x] Set up config generation (built-in)
- [x] Create prompt for `new`
- [x] Read selected template 
- [x] Generate project structure
- [x] Set up build the executable 
- [x] Set up running (simple mode: only run the pre-generated executable or generate if it doesn't exist)

**Comment by hrszpuk** [comment]
Gonna start with a simple, normal prompt and then make it better with BubbleTea later probably.
