### ISSUE TITLE
LICENSE generation with meta-variables

### ISSUE THREAD

**Issue by hrszpuk** [hrszpuk/rectx#56]
**Is your feature request related to a problem? Please describe.**
LICENSE generation was an original aim for ReCTx version 2.0.0.

**Describe the solution you'd like**
The solution is fairly simple, the user will be able to select any license available through rectx (or simple choose to not generate any license), then during project generation, a LICENSE file will be generated.

**Comment by hrszpuk** [comment]
TO DO:
- [ ] Finish licenses.GenerateLicense
- [ ] Add Prompt to Project Generation in project_manager.New
- [ ] Hook up license generation to the project generator
- [ ] Add meta-variable calls to license generation
