### ISSUE TITLE
Generating compilation directories,  and dependency management

### ISSUE THREAD

**Issue by hrszpuk** [hrszpuk/rectx#8]
## Generating directories
Directory generation is usually handled by the `manager` module. In this case, a `target/` directory should be generated with the executable of the correct name inside. Each compilation profile, currently only `run` and `build`, should generate their own directory `target/run/` and `target/build/` respectfully. This will involve modifying `manager::generate_project_executable()`.

In addition to the `target/` directory a `deps/` (for storing dependencies or files that are needed at runtime) should be generated during project creation (i.e. `rectx new project-name`). Any files inside the `deps/` directory should be **copied** into the `target/build/`/`target/run/`. 

### Milestone reference (#1)
This is the last feature needed for the v1.0.0 milestone to be complete and is referenced on the v1.0.0 section as "Add target/" and "Add /deps".

### Tasks
- [x] Generate deps/ during `manager::generate_project_directory()`
- [x] Generate target/ during `manager::generate_project_executable()`
    - [x] Generate target/
    - [x] Generate correct compilation profile directory
    - [x] Compile program into target/{run/build}
- [x] Copy dependencies from deps/ into target/{run/build}

**Comment by hrszpuk** [comment]
Note: when I mean `/target` I mean the output_dir in the compilation profile.
Perhaps `target/` and `deps/` should be defined within `[project]` not inside the profiles?
Can't think of a reason you'd want different output directories for specific profiles over an overall project one :/ ...

**Comment by mauro-balades** [comment]
why would you have `/target/run`? you could just build it as normal and then execute the output 👍🏽
